# plot3.R
url <- "http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
f <- file.path(getwd(), "data_file.zip")
download.file(url, f)
unzip(data_file.zip)
library(dplyr)
df <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE)
data <- tbl_df(df)
rm(df)
plotdata <- filter(data, as.Date(data$Date,"%d/%m/%Y") == "2007-02-01" | as.Date(data$Date,"%d/%m/%Y") == "2007-02-02")
rm(data)
plotdata$Datetime <- as.POSIXct(paste(plotdata$Date, plotdata$Time), format = "%d/%m/%Y %H:%M:%S") 
plot(plotdata$Datetime, as.numeric(plotdata$Sub_metering_1), type = "n", xlab = " ", ylab = "Energy Sub metering")
lines(plotdata$Datetime, as.numeric(plotdata$Sub_metering_1))
lines(plotdata$Datetime, as.numeric(plotdata$Sub_metering_2), col = "red")
lines(plotdata$Datetime, as.numeric(plotdata$Sub_metering_3), col = "blue")
legend("topright", pch = "", lwd=1, col = c("black","red","blue"), legend = c("Sub_metering_1   ","Sub_metering_2   ","Sub_metering_3   "))
dev.copy(png, "plot3.png")
dev.off()